# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 痴人说梦 Tachiguishi's Nonsense
email: TachiguishiRor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tchiguishi's blog.
  A palce you can find my programming journey.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tachiguishi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RorSipke
github_username: Tachiguishi
disqus:
  shortname: RorSpike

paginate: 20

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false

default:
  -
    scope:
      path: "_posts" # 一个空的字符串代表项目中所有的文件
      # type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      comments: true
# gems:
  # - jekyll-coffeescript
